version: "3"

networks:
  revProxy-net:
    external: true

secrets:
   db_password:
     file: db_password.txt

services:
  yt-db:
    image: postgres:14.10-alpine3.18
    container_name: yt-db
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
    networks:
      - revProxy-net
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql/data

  yt-db-backup:
    container_name: ytdiff_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    secrets:
      - db_password
    environment:
      POSTGRES_HOST: yt-db
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      TZ: Asia/Kolkata
      BACKUP_KEEP_DAYS: 4
      BACKUP_KEEP_WEEKS: 3
      BACKUP_KEEP_MONTHS: 2
      SCHEDULE: "0 0 * * *"
      BACKUP_NUM_KEEP: 3
      BACKUP_DIR: /db_dumps
    volumes:
      - ${DB_DUMP_LOCATION}/db_dumps:/db_dumps
    depends_on:
      - yt-db
    restart: always
    networks:
      - revProxy-net

  yt-diff:
    image: purevert/yt-diff:alpine-amd64
    container_name: yt-diff
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - base_url=${BASE_URL}
      # Use this to modify the files during building
    volumes:
      - ${HOST_SAVE_PATH}:/${SAVE_PATH}
      #- ./dist:/dist
    depends_on:
      - yt-db
    networks:
      - revProxy-net
    # expose:
    #   - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - host=${HOSTNAME}
      - protocol=${PROTOCOL}
      - base_url=${BASE_URL}
      - db_host=${DB_HOST}
      - db_user=${DB_USERNAME}
      - db_password=/run/secrets/db_password
      - port=${PORT}
      - hide_ports=${HIDE_PORTS}
      - save_loc=${SAVE_PATH}
      - sleep=${SLEEP}
      - chunk_size_env=${CHUNK_SIZE}
      - subtitles=${SAVE_SUBSTITLES}
      - description=${SAVE_DESCRIPTION}
      - comments=${SAVE_COMMENTS}
      - thumbnail=${SAVE_THUMBNAIL}
      - time_zone=${TZ_PREFERRED}
      - scheduled=${UPDATE_SCHEDULED}
    secrets:
      - db_password
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ytdiff.entryPoints=web,websecure'
      - 'traefik.http.routers.ytdiff.rule=Host(`${HOSTNAME}`) && PathPrefix(`${BASE_URL}`)'
      - "traefik.http.services.ytdiff.loadbalancer.server.port=${PORT}"
      - 'traefik.http.services.ytdiff.loadBalancer.passHostHeader=true'
      - "traefik.http.routers.ytdiff.middlewares=http-to-https@docker"
      - "traefik.http.routers.ytdiff.tls=true"
      - "traefik.http.routers.ytdiff.tls.certresolver=tailsolver"
      - "traefik.http.routers.ytdiff.tls.domains[0].main=${HOSTNAME}"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/ytdiff"]
      interval: 5m
      timeout: 5s
      start_period: 30s
      retries: 3

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    depends_on:
      - yt-db
    ports:
      - 9090:8080
    networks:
      - revProxy-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.entryPoints=web,websecure'
      - 'traefik.http.routers.adminer.rule=Host(`${HOSTNAME}`) && PathPrefix(`/adminer`)'
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - 'traefik.http.services.adminer.loadBalancer.passHostHeader=true'
      - "traefik.http.middlewares.strip-adminer.stripprefix.prefixes=/adminer"
      - "traefik.http.routers.adminer.middlewares=strip-adminer@docker,http-to-https@docker"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=tailsolver"
      - "traefik.http.routers.adminer.tls.domains[0].main=${HOSTNAME}"
