version: '3'
services:
  diff-maker:
    image: purevert/yt-diff
    container_name: yt-diff
    network_mode: service:vpn-proton
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./yt-dlp:/home
    privileged: true

  vpn-proton:
    image: qmcgaw/gluetun
    container_name: vpn-proton
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=${SERVICE_PROVIDER_VPN}
      - OPENVPN_USER=${USERNAME_VPN}
      - OPENVPN_PASSWORD=${PASSWORD_VPN}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES_PREFERRED}
      - FREE_ONLY=${FREE}
      - Tz=${TZ_PREFERRED}
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: "unless-stopped"

  db:
    image: postgres:14
    container_name: postgres-diff
    network_mode: service:vpn-proton
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  pgdata:
