version: "3"
services:
  database:
    image: postgres:13.9-alpine3.17
    container_name: yt-db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./ytdata:/var/lib/postgresql/data

  diff-maker:
    image: purevert/yt-diff
    container_name: yt-diff
    # network_mode: service:vpn-proton
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./yt-dlp:/yt-dlp
    depends_on:
      - database
    ports:
      - 8888:8888
    privileged: true

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  #http://localhost:8080/?pgsql=database&username=ytdiff&db=vidlist&ns=public

  #vpn-proton:
  #  image: qmcgaw/gluetun
  #  container_name: vpn-proton
  #  cap_add:
  #    - NET_ADMIN
  #  env_file:
  #    - .env
  #  environment:
  #    - VPN_SERVICE_PROVIDER=${SERVICE_PROVIDER_VPN}
  #    - OPENVPN_USER=${USERNAME_VPN}
  #    - OPENVPN_PASSWORD=${PASSWORD_VPN}
  #    - SERVER_COUNTRIES=${SERVER_COUNTRIES_PREFERRED}
  #    - FREE_ONLY=${FREE}
  #    - Tz=${TZ_PREFERRED}
  #  devices:
  #    - /dev/net/tun:/dev/net/tun
  #  volumes:
  #    - ./gluetun:/gluetun
  #  ports:
  #    - 9091:9091
  #    - 51413:51413
  #    - 51413:51413/udp
  #  restart: "unless-stopped"

  # will implement later
#volumes:
#  ytdata:
