name: Prune Registry

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * *
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  prune-images:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.PRUNE_TOKEN }}
          user: sagnikdas53
          container: yt-diff
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 0 # days
          keep-last: 6
          prune-untagged: true
          keep-tags-regexes: |
            ^pr-

